name: CI
on:
    push:
        paths: ["*.S"]
    pull_request:
        paths: ["*.S"]
jobs:
    quick-bench:
        runs-on: date
        steps:
            - uses: actions/checkout@v5
            - run: |
                  nix build --builders "" .#packages.x86_64-linux.fasmfetch
                  nix shell --builders "" nixpkgs#hyperfine nixpkgs#fastfetch \
                      --command hyperfine --warmup=50 --runs=100 --shell=none \
                      "./result/bin/fasmfetch" "fastfetch" > result.txt
                      cat result.txt
